#include <iostream>
using namespace std;

void f(int test)
{
  try{
    if(test) throw test;
  }
  catch(int i) {
    cout << "Caught Exception #: " << i << '\n';
  }
}

int main()
{
  cout << "Start\n";

  f(1);
  f(2);
  f(0);
  f(3);

  cout << "End";

  return 0;
}
